### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by TJ-C** [emoncms/emoncms-docker#10]
Hi, I'm running docker for Mac and I receive the following error after connecting to localhost:8080:
"settings.php file error

settings.php config file has new settings for this version. Copy default.settings.php to settings.php and modify the later.

homedir is not configured or directory does not exists, check settings: homedir

To fix, check that the settings are set in settings.php or try re-creating your settings.php file from default.settings.php template"

Connecting to the web container, there is no home dir and none of the docker files creates the home dir. In the default.settings.php where should the $homedir point to?

If i manually create the home dir in the container, then I am still left with the error:
"settings.php file error

settings.php config file has new settings for this version. Copy default.settings.php to settings.php and modify the later.

To fix, check that the settings are set in settings.php or try re-creating your settings.php file from default.settings.php template"

**Comment by Paul-Reed** [comment]
...and have you done what the message is telling you - "Copy default.settings.php to settings.php and modify the latter" ?

**Comment by TJ-C** [comment]
When I do that I receive the following error:
Can't connect to database, please verify credentials/configuration in settings.php
Error message: No such file or directory

Also in the Dockerfile it has the following:
# Copy in settings from defaults
WORKDIR /var/www/html
RUN cp default.settings.php settings.php

So I am assuming that the default.settings.php file has some missing info.

**Comment by Paul-Reed** [comment]
Are your MYSQL credentials correct in your settings file, as per the
message?

**Comment by Trickx** [comment]
I'm running into the same issues.
What are the default mysql credentials and how may change them?
Is there aleready the database "emoncms"?
As far as I can see, the mysql database is not accessible from the host, just from the network "emoncmsdocker_default" the containers are running in.
From the docker console, I found a newly generated root password for mysql.
But I can't connect to the server e.g. with Sequel due to the mentioned networking issue.
How do I connect to mysql from outide docker?
